---
title: "correlación"
author: "Manuel Martín"
date: "2024-02-26"
output: html_document
---

###Ejercicio 1

```{r, echo=True}
library(readxl)
data <- as.data.frame(read_excel("C:/Users/manueltristan/Documents/correlacion/data.xlsx"))
View(data)
print(data)
```

```{r}
#Función para agregar coeficientes de correlación
panel.cor <- function(x, y, digits = 2, prefix = "", cex.cor, ...) {
  usr <- par("usr")
  on.exit(par(usr))
  par(usr = c(0, 1, 0 ,1))
  Cor <- abs(cor(x, y)) 
  txt <- paste0(prefix, format(c(Cor, 0.123456789), digits = digits)[1])
  if(missing(cex.cor)) {
    cex.cor <- 0.4 / strwidth(txt)
  }
  text(0.5, 0.5, txt,
       cex = 1 + cex.cor*Cor)
}
#Dibujamos la matriz de correlación
pairs(data,
      upper.panel = panel.cor, # Panel de correlación
      lower.panel = panel.smooth) #Curvas de regresión suavizadas
```

```{r, echo=True}
cor.test(data$longitud, data$peso)
```

```{r, warning=FALSE}
library(correlation)
resultados <- correlation(data)
resultados
```
```{r, echo=TRUE}
library(ggpubr)
library(ggplot2)
ggscatter(data, x = "longitud", y = "peso",
          add = "reg.line", conf.int = TRUE,
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "longitud piezas (mm)", ylab = "Peso piezas (mg)")
```

```{r }
library(corrplot)
corrplot(cor(data))
```
```{r }
library(corrplot)
corrplot.mi(cor(data))
```
### Ejercicio VI

A partir de las siguientes variables

- Distancia (km): 1.1,100.2,90.3,5.4,57.5,6.6,34.7,65.8,57.9,86.1
- Número de cuentas (valor absoluto): 110,2,6,98,40,94,31,5,8,10

a. Crea 2 vectores: "distancia" y "n_piezas"

```{r }
distancia <- c(1.1,100.2,90.3,5.4,57.5,6.6,34.7,65.8,57.9,86.1)
n_piezas <- c(110,2,6,98,40,94,31,5,8,10)
dist_ncuent <- data.frame(distancia,n_piezas)
knitr::kable(dist_ncuent)
```